---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-window-open-cluster-management-io-v1alpha1-maintenancewindow
  failurePolicy: Fail
  name: vmaintenancewindow.kb.io
  rules:
  - apiGroups:
    - window.open-cluster-management.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - maintenancewindows
  sideEffects: None
