---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - window.open-cluster-management.io
  resources:
  - maintenancewindows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - window.open-cluster-management.io
  resources:
  - maintenancewindows/finalizers
  verbs:
  - update
- apiGroups:
  - window.open-cluster-management.io
  resources:
  - maintenancewindows/status
  verbs:
  - get
  - patch
  - update
